export const APP_PERMISSIONS = [
  { key: 'dashboard.view', label: 'Xem dashboard', group: 'Dashboard' },
  { key: 'employees.read', label: 'Xem nhan vien', group: 'Nhan vien' },
  { key: 'employees.create', label: 'Tao nhan vien', group: 'Nhan vien' },
  { key: 'employees.update', label: 'Cap nhat nhan vien', group: 'Nhan vien' },
  { key: 'employees.delete', label: 'Xoa nhan vien', group: 'Nhan vien' },
  { key: 'branches.read', label: 'Xem chi nhanh', group: 'Chi nhanh' },
  { key: 'branches.create', label: 'Tao chi nhanh', group: 'Chi nhanh' },
  { key: 'branches.update', label: 'Cap nhat chi nhanh', group: 'Chi nhanh' },
  { key: 'branches.delete', label: 'Xoa chi nhanh', group: 'Chi nhanh' },
  { key: 'outlets.read', label: 'Xem cua hang', group: 'Cua hang' },
  { key: 'outlets.create', label: 'Tao cua hang', group: 'Cua hang' },
  { key: 'outlets.update', label: 'Cap nhat cua hang', group: 'Cua hang' },
  { key: 'outlets.delete', label: 'Xoa cua hang', group: 'Cua hang' },
  { key: 'tasks.read', label: 'Xem cong viec', group: 'Cong viec' },
  { key: 'tasks.create', label: 'Tao cong viec', group: 'Cong viec' },
  { key: 'tasks.update', label: 'Cap nhat cong viec', group: 'Cong viec' },
  { key: 'tasks.delete', label: 'Xoa cong viec', group: 'Cong viec' },
  { key: 'reports.read', label: 'Xem bao cao', group: 'Bao cao' },
  { key: 'reports.approve', label: 'Duyet bao cao', group: 'Bao cao' },
  { key: 'surveys.read', label: 'Xem khao sat', group: 'Khao sat' },
  { key: 'surveys.manage', label: 'Quan ly khao sat', group: 'Khao sat' },
  { key: 'devices.read', label: 'Xem thiet bi', group: 'Thiet bi' },
  { key: 'devices.manage', label: 'Quan ly thiet bi', group: 'Thiet bi' },
  { key: 'positions.read', label: 'Xem chuc vu', group: 'Phan quyen' },
  { key: 'positions.manage', label: 'Quan ly chuc vu va phan quyen', group: 'Phan quyen' },
] as const;

export const APP_PERMISSION_KEYS = APP_PERMISSIONS.map((permission) => permission.key);
